#spring.application.name=siderandinaMSEureka
server:
  port: 8761

spring:
  application:
    name: siderandinaMSEureka
  config:
    import: 'optional:configserver:http://localhost:8888'

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultzone: http://localhost:${server.port}/eureka/
