#spring.application.name=siderandinaMSCompras

server:
  port: 9090

spring:
    application:
        name: siderandinaMSCompras
    config:
        import: "optional:configserver:http://localhost:8888"
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://ep-floral-paper-acuw88rx-pooler.sa-east-1.aws.neon.tech:5432/neondb
        username: neondb_owner
        password: npg_lw0TotXrsIk9
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

