server:
  port: 8082 

spring:
  application:
    name: siderandinaMSVenta
  datasource:
    url: jdbc:h2:mem:ventasdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuración para consumir el MSRRHH
msrrhh:
  url: http://localhost:9080