#spring.application.name=siderandinaMSConfig

server:
  port: 8888

spring:
    application:
        name: siderandinaMSConfig
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configurations
                    