#spring.application.name=siderandinaMSRRHH
server:
  port: 9080
spring:
  application:
    name: siderandinaMSRRHH
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://swuV8pWQKfZu1b4.root:HTepP2daTDWyfnq0@gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
    username: swuV8pWQKfZu1b4
    password: HTepP2daTDWyfnq0
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

